# SPDX-FileCopyrightText: 2022 RTE FRANCE
#
# SPDX-License-Identifier: Apache-2.0

name: Release Project

on:
  release:
    types: [ released ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Extract tag name
        id: extract_tagname
        shell: bash
        # Extra the tagname form the git reference, value of GITHUB_REF will be something like refs/tags/<tag_name>.
        run: echo "##[set-output name=tagname;]$(echo ${GITHUB_REF##*/})"

      # Deploy to Maven Central Repository
      - name: Set up Java JDK 1.11 for publishing to Maven Central Repository
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Set version with Maven
        run: mvn -B versions:set -DprocessAllModules=true -DnewVersion=${{ steps.extract_tagname.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      # Deploy to GitHub Packages
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
          distribution: 'zulu'
          server-id: github-packages-compas
          server-username: GITHUB_USERNAME
          server-password: GITHUB_TOKEN
      - name: Set version with Maven
        run: mvn -B versions:set -DprocessAllModules=true -DnewVersion=${{ steps.extract_tagname.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_USERNAME: "OWNER"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}